import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all the assets generated by the build process.
precacheAndRoute([{"revision":"7195b335fa7f9f2a231dc43b45168c5d","url":"index.html"},{"revision":"33dbdd0177549353eeeb785d02c294af","url":"logo192.png"},{"revision":"917515db74ea8d1aee6a246cfbcc0b45","url":"logo512.png"},{"revision":"59611a3b010985e1ca9856064e79b162","url":"static/css/main.4188f58f.css"},{"revision":"96ff25d65ae30f802c4e832a92f19950","url":"static/js/787.8e580187.chunk.js"},{"revision":"9aa96b82bb28ff54eac7c12f79b6bfe4","url":"static/js/main.b1fcdffc.js"}]);

// Cache CSS and JS files with a stale-while-revalidate strategy.
registerRoute(
  ({ request }) => request.destination === 'style' || request.destination === 'script',
  new StaleWhileRevalidate()
);

// Cache image files with a cache-first strategy.
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);